/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include "pn532.h"
#include "UART2.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SPI_Config(SPI_HandleTypeDef *hspi);


int main(void)
{
	HAL_Init();

	//SS versnellingsmeter (PE3) hoog maken om verstoringen op SPI1 te mijden
	__HAL_RCC_GPIOE_CLK_ENABLE();
	GPIO_InitTypeDef GPIO_Init_PE3 = {0};
	GPIO_Init_PE3.Mode = GPIO_MODE_OUTPUT_PP; //OUTPUT Push Pull Mode
	GPIO_Init_PE3.Pin = GPIO_PIN_3;
	GPIO_Init_PE3.Pull = GPIO_NOPULL;

	HAL_GPIO_Init(GPIOE, &GPIO_Init_PE3);
	HAL_GPIO_WritePin(GPIOE, GPIO_PIN_3, GPIO_PIN_SET);




	//SPI1 configuratie
	__HAL_RCC_GPIOA_CLK_ENABLE(); //RCC klok op poort A activeren
	SPI_HandleTypeDef hspi = {0};
	SPI_Config(&hspi);

	//PN532
	PN532_Handle hpn532 = {0};
	hpn532.protocol = PN532_SPI;
	hpn532.mode = PN532_MODE_NORMAL;
	hpn532.interface.spi.hspi = &hspi;
	hpn532.interface.spi.ss_pin = GPIO_PIN_15;
	hpn532.interface.spi.ss_port = GPIOE;

	//Blauwe User button configureren
	GPIO_InitTypeDef GPIO_Init_PA0 = {0};
	GPIO_Init_PA0.Mode = GPIO_MODE_INPUT;
	GPIO_Init_PA0.Pin = GPIO_PIN_0;
	GPIO_Init_PA0.Pull = GPIO_PULLDOWN; //pulldown weerstand
	GPIO_Init_PA0.Speed = GPIO_SPEED_FREQ_LOW;

	HAL_GPIO_Init(GPIOA, &GPIO_Init_PA0);

	PN532_Init(&hpn532);
	UART_Init();

	//Variables
	uint8_t pushed = 0;

	while(1){
    	if(HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0) == GPIO_PIN_SET){
    		HAL_Delay(20);

    		if (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0) == GPIO_PIN_SET)
			{
				char testID[] = "ID:45A2C133\n";
				UART_SendString(testID);


				while (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0) == GPIO_PIN_SET); //Checken op loslaten
			}
		}
    }
}

void SPI_Config(SPI_HandleTypeDef *hspi){
	__HAL_RCC_SPI1_CLK_ENABLE(); //RCC klok activeren

	//GPIO Pin-Configuraties SPI1: SCK -> PA5 AF5, MISO -> PA6 AF5, MOSI -> PA7 AF5
	GPIO_InitTypeDef GPIO_Init = {0};
	GPIO_Init.Pin = GPIO_PIN_5;
	GPIO_Init.Mode = GPIO_MODE_AF_PP; //AF mode want pin moet worden bestuurd door SPI
	GPIO_Init.Pull = GPIO_NOPULL;
	GPIO_Init.Alternate = GPIO_AF5_SPI1; //AF5 zie manual
	GPIO_Init.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	HAL_GPIO_Init(GPIOA, &GPIO_Init);

	GPIO_Init.Pin = GPIO_PIN_6;
	HAL_GPIO_Init(GPIOA, &GPIO_Init);

	GPIO_Init.Pin = GPIO_PIN_7;
	HAL_GPIO_Init(GPIOA, &GPIO_Init);

	//Slave Select Pin PE15 voor PN532
	GPIO_Init.Pin = GPIO_PIN_15;
	GPIO_Init.Mode = GPIO_MODE_OUTPUT_PP;
	GPIO_Init.Alternate = 0;
	GPIO_Init.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(GPIOE, &GPIO_Init);

	HAL_GPIO_WritePin(GPIOE, GPIO_PIN_15, GPIO_PIN_SET); //slave select default high

	hspi->Instance = SPI1;
	hspi->Init.Mode = SPI_MODE_MASTER;
	hspi->Init.Direction = SPI_DIRECTION_2LINES; //full duplex
	hspi->Init.CLKPolarity = SPI_POLARITY_LOW; //PN532 werkt op mode1 cpol=0
	hspi->Init.CLKPhase = SPI_PHASE_1EDGE; //cpha=0
	hspi->Init.DataSize = SPI_DATASIZE_8BIT; //PN532 accepteert 8-bit-pakketten
	hspi->Init.NSS = SPI_NSS_SOFT; //software slave management inschakelen -> selectie via gpio pin
	hspi->Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_8; //PN532 ondersteunt tot 5MHZ -> 16MHZ/8=2MHZ
	hspi->Init.FirstBit = SPI_FIRSTBIT_LSB; //PN532 gebruikt LSBFIRST

	HAL_SPI_Init(hspi);
}






